### ISSUE TITLE
Issues with genre channels

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#183]
As you [mentioned earlier](https://github.com/omarroth/invidious/issues/119#issuecomment-418576624), there are still a few problems with genre channels:
* Invalid (non-existed) channel URLs for some topics, such as [Education](https://www.youtube.com/channel/UC3yA8nDwraeOfnYfBWun83g);

I suggest to remove them if it's possible.
* Empty `/videos` pages for channels, such as [News channel](https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw/);

I think it's better to add some sort of content to these pages, e.g. videos from playlists `Top Stories` and `Live Now`.

**Comment by omarroth** [comment]
The issue with non-existent URLs should be fixed with c2e7243.

I agree it would be good to have content for News. The channel itself seems like a very strange edge-case. Clicking on `playlists` will not show the `top stories` playlist available on the homepage. I think this is connected to a larger issue of being able to access channel info, playlists, etc from the `/channel` page.

**Comment by omarroth** [comment]
Genre channels should now correctly display a list of playlists, rather than an empty list of videos. [Larger auto-generated channels](https://invidio.us/channel/UCYfdidRxbB8Qhf0Nx7ioOYw/) and [topic Channels](https://invidio.us/channel/UCE80FOXpJydkkMo-BYoJdEg) should work as expected.

Since the mentioned problems appear to be fixed I'm going to close this. 

Subscribing to genre channels will be handled in #17, and will probably be the same as if you had subscribed to the `Latest videos` playlist available on most genre channels.

**Comment by chaosmonk1** [comment]
> topic channels should work as expected.

"* - Topic" channels for music artists still appear empty. For example,
https://invidio.us/channel/UCZxwihQYwXEogN-DGfngwcw
although videos from these channels are accessible.
https://invidio.us/watch?v=4VxY0ZoR6SI

**Comment by omarroth** [comment]
Should be fixed with 2ebc773863b13091d12439b24bb73ce1a012f11c. Albums currently aren't viewable from the channel page since they use a different thumbnail endpoint that isn't supported yet.
