### ISSUE TITLE
Autoplay doesn't work in listen mode

### ISSUE THREAD

**Issue by Emaro** [omarroth/invidious#242]
Videos do not start playing automatically when setting the "Listen by default" option or when navigating to the audio version of a video.

Win10, Opera 56

**Comment by omarroth** [comment]
Should be fixed with 7ab9d74.

**Comment by Emaro** [comment]
Thank you, I'll check it out.

**Comment by IzzySoft** [comment]
I still have this issue in latest Waterfox (56.2.7.1) on Win 10. Next video is loaded, but not started. I've checked with uBlock Origin as well as uMatrix, nothing is blocked there. The "Autoplay next video" box is checked, also in preferences. I'm using the `invidio.us` site.

**Comment by Emaro** [comment]
Working.

**Comment by AMDG2** [comment]
It is still failing on my side with the following error message in JS console:

![Capture d’écran du 2019-06-17 20-19-17](https://user-images.githubusercontent.com/1136402/59626861-3a615280-913d-11e9-99a9-2056469d9ce8.png)

My environment:
- ArchLinux
- Firefox 67.0.2
- Invidious version: 0.18.0-bbb40ae master

I can provide more info if needed, I can reproduce the issue 100% of the times. Step to reproduce:

1. Enable *autoplay*, *listen mode* and *Play next by default* in settings
2. Open any video, doesn't start
3. Start it
4. At the end wait until next video loads
5. Next video doesn't start neither (same error message in console)

**Comment by omarroth** [comment]
My understanding is that Firefox (for most sites) has autoplay disabled by default. You might take a look at [this comment](https://github.com/omarroth/invidious/issues/7#issuecomment-490535330) for more information.

**Comment by Perflyst** [comment]
You can give any site permission to do autoplay. The same way as you can give permission for notifications.

**Comment by AMDG2** [comment]
Yes, I just noticed the icon today to enable autoplay for invido.us. I was searching for it this week-end didn't find it.

**Comment by Kiude** [comment]
Hi ! Firefox user here, on the snopyta.org instance.
I'm having the same problem with the autoplay video mode.

I tried the trick with giving exception permission as explained here : https://support.mozilla.org/en-US/kb/block-autoplay#w_add-sites-to-your-list-to-autoplay-media

But nothing. The next video does open, but get stuck, waiting for me to click on it.
The solution here https://github.com/omarroth/invidious/commit/8861d31b217180f1f37a262b9af3ffd075fa0497 goes beyond my digital competency Im afraid. Did it solve it for the people who used it ?

**Comment by IzzySoft** [comment]
@Kiude feel free to replace that addon by a userscript. I've no such issues using mine: [YT2Invidio](https://greasyfork.org/de/scripts/374833-yt2invidio). It doesn't cover all of the features [Invidition](https://addons.mozilla.org/en-US/firefox/addon/invidition/) has, though (e.g. no instance selection or default subtitles). It simply redirects all YT links to invidio.us (you can adjust the instance inside the script easily).

**Comment by Kiude** [comment]
Thank you for your answer IzzySoft ! I just stumbled upon the solution.. which left me quite embarrassed...
Indeed, Invidition users need not only to change the addon autopay settings, and not only the Invidious page ones.. Addon settings seem to over-ride the latter.

So yeah, problem solved!

**Comment by IzzySoft** [comment]
@Kiude Glad to read! And I like your "autopay settings". Could you put my account data on the receiving end? 🤣

**Comment by Kiude** [comment]
Sure, just send me your bank information, and a photo of both sides of your credit card also  xD  ^ ^

I realize I got quite confused on my explanation and made some grammar mistakes.. my bad! I'll try to focus more next time ^^"

**Comment by IzzySoft** [comment]
I was just kidding, no blame intended. All was clear – forgive me for jumping on this but it was too tempting…

**Comment by Kiude** [comment]
No worries, I actually like to write properly : it's more a favor that you gave me haha
