### ISSUE TITLE
Content warning error

### ISSUE THREAD

**Issue by Jtasiu** [omarroth/invidious#371]
I came across content message warning viewed a video..I assume it was age-restricted. Is there a way or some parameter available so I can watch the video without seeing that error?

**Comment by omarroth** [comment]
Which video are you trying to watch?

**Comment by omarroth** [comment]
Should be fixed with 0c8dff162d2431e087b28f334827dbe3a65a233e. I've encountered several videos which youtube-dl is also not able to download, but the majority of videos that had this issue should now work.

**Comment by Perflyst** [comment]
This one does not work, is it possible to bypass the login? https://www.youtube.com/watch?v=j1SIDatfBOU

**Comment by Mrfiregem** [comment]
Error still appears, but now for videos marked private, e.g: https://www.youtube.com/watch?v=TyusU4Bvdvo
