### ISSUE TITLE
Notifications create tons of connections in the background

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#590]
As seen here:
![image](https://user-images.githubusercontent.com/16914176/59192460-d231d000-8b82-11e9-9e6e-993a66cce8f1.png)

After leaving the tab in the background for a while, it spams the site with tons of `/v1/auth/subscriptions` requests, all of which time out.  
Because of this, trying to open another video in a new tab hangs on `Waiting for available socket...` forever.

Note that `Pulling subscriptions timed out... 1/10` is logged at the same time by 30 separate cancellations, and none of them increase the counter.

Completed requests also error with `ERR_INCOMPLETE_CHUNKED_ENCODING` quite often.

Tested on Chromium latest, but encountered on Waterfox 56 as well.

**Comment by omarroth** [comment]
Should be fixed with 552f616305809d111f7540cbea93f89fad3d0760.

**Comment by Discookie** [comment]
The timeout countdown now works well, but the connections are still there, and it still takes an absurdly long time for them to time out. And even after the 1/5 timeout, sockets are still not available.

![image](https://user-images.githubusercontent.com/16914176/59565423-d57dfd80-9053-11e9-852d-98475857fe7d.png)

It might not be only the notifications hogging up the sockets, however. But I don't know what else stays open in the background, and I can't see anything else being opened, or being slow. I'm using the DASH player if that matters.

**Comment by Discookie** [comment]
![image](https://user-images.githubusercontent.com/16914176/59566006-46c0af00-905a-11e9-92f4-1c14bc0830a1.png)

Note that the number of /subscriptions requests increases exponentially, because all of the /notifications requests fail with INCOMPLETE_CHUNKED_ENCODING, and they always retry without a limit or a timeout.

**Comment by omarroth** [comment]
I'm having trouble reproducing locally, how long do you normally have the tab in the background before encountering this?

Pushed a couple more changes with 17edfd65736fde44d16e5fe9b4e68e637246a127 which should help.

**Comment by Discookie** [comment]
12.2 minutes, acording to Dev Tools.

I've saved the stack traces for the first 2 "retries": https://pastebin.com/2uQfibgM  
It looks like notifications.onerror is being called twice on the stream erroring?

**Comment by omarroth** [comment]
I left the tab open in the background for a couple hours. It disconnected a couple times but reconnected successfully without issue.

> I've saved the stack traces for the first 2 "retries": https://pastebin.com/2uQfibgM

It looks like you still have an older version. Latest is `notifications.js?v=2e1f9d5`.

**Comment by Discookie** [comment]
It was the latest commit that touched notifications.js/sse.js when I tested it: https://github.com/omarroth/invidious/commit/9dea2518625323e34ff5103135ac29114c9b3f82
But I'll re-test with the current one just in case.

I'm not sure timeouts count as errors, is there any way that you can *force* an error to test it with?  
I'm not sure what causes ERR_INCOMPLETE_CHUNKED_ENCODING, but that's what interrupts my connections, usually not a timeout. Timeouts only start occuring when there's 10+ connections open at the same time.

**Comment by omarroth** [comment]
Typing `notifications.close()` in the console should trigger an error for you to test with.

Generally `ERR_INCOMPLETE_CHUNKED_ENCODING` means the connection was closed or reset, which can happen for a couple reasons, and becomes more likely the longer a connection is open.

**Comment by Discookie** [comment]
When loading the page, 1 connection is created to `/notifications`, that is connection 1.
The first time I type `notifications.close();`, 
  * it closes connection 1, 
  * it calls `notifications.onerror` 2 times, with the same stack trace I linked above,
  * Which, in turn start connections 2 and 3, so I now have 2 connections.

If I call `notifications.close();` again:
  * It closes connection 3, but keeps 2 alive
  * It triggers notifications.onerror 2 times again, starting connections 4 and 5
  * So now I have 3 active connections: 2, 4, 5

If I call it again, 5 is closed, but 6 and 7 is started, totalling in 4 connections: 2, 4, 6, 7;  
et cetera, until I have too many open connections to invidious, and I cannot load any more pages.

**Comment by omarroth** [comment]
I'm having trouble reproducing in Waterfox 56.2.10.1 or Chromium 75.0.3770.90, but bbb40aef5125d5ff2751337d0f1b8b06d7f0a660 should prevent `onerror` from being called twice.

**Comment by Discookie** [comment]
I'm having trouble reproducing on Waterfox now as well, one of the previous fixes must've fixed the issue there. But on my Chromium 75.0.3770.90, I can reproduce it every time.

Some more information about the calls:
  * After calling `xhr.abort()`, a ProgressEvent of type "progress" is fired, calling `_onStreamProgress`.  
But, by the time the ProgressEvent is fired, `xhr.status` is changed to 0, so it calls `_onStreamFailure` the first time.
  * After that is done, still within `xhr.abort()`, a ProgressEvent of type "abort" is fired, calling `_onStreamFailure` for the second time.

I'm not sure why that extra "progress" event is thrown, but it's definitely something to handle.

**Comment by omarroth** [comment]
cc6d6ddd66b56b8c234c2af19cc38a4c1d26c9f2 should prevent the extra "progress" event from being fired.

**Comment by Discookie** [comment]
Thank you! Now it works flawlessly.
