### ISSUE TITLE
"Video unavailable." on every video.

### ISSUE THREAD

**Issue by gwennshinguji** [omarroth/invidious#644]
I keep getting this same error message with all my addons disabled, using both a Chrome-based and Firefox browser.
I am on Manjaro XFCE.
Even if I'm logged out, I get this error. I sent an [invidio.us](https://invidio.us/) link to a friend and he couldn't access it either. I am in the US and so is he. Is this site just dead now?

**Comment by Brn9hrd7** [comment]
I'm having the same issue, and it looks like all invidious instances are affected. I'm from Europe, so it's not a US-only restriction or something like that.

**Comment by eTzmNcbkrng** [comment]
Same issue in New Zealand.

**Comment by sseneca** [comment]
Same in the UK — I imagine the G changed something on their end.

**Comment by gwennshinguji** [comment]
Seems to be fixed for me, how about you guys?

**Comment by omarroth** [comment]
Should be fixed with ff5d79e3ee1d295e97e589e39ca09bd0a880c99f.

**Comment by CuloArdido** [comment]
It still fails with these links:
https://invidio.us/watch?v=Jh343syvDBI
https://invidio.us/watch?v=iviMvbECqEE
And possibly with all those who have content warnings. Normal videos seem to work already

**Comment by omarroth** [comment]
Gotcha, should be fixed with 0321dda1d76cb17a20b90a0fe26542dd5b3af0d0.
