### ISSUE TITLE
"Seasons" playlists are broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#702]
The "Seasons" playlists are not displayed on the channel playlists page, and when searched are shown with 0 videos : 

Here the "Nostalgia Critic" one : 
![Season](https://user-images.githubusercontent.com/47571719/63182760-d080fe80-c042-11e9-9ce8-f887e42bcc82.png)

The links of the 12 Seasons : 
https://www.youtube.com/playlist?list=PL0AQIMR-tponPuCDBwwC6TGohOp0W_ozX
https://www.youtube.com/playlist?list=PL0AQIMR-tpokLMCidVcI5ESIDq_U_IhqD
https://www.youtube.com/playlist?list=PL0AQIMR-tpomYJhfr6eE0SZwYJjmUX2l3
https://www.youtube.com/playlist?list=PL0AQIMR-tpol8YUnAMlw---V8rb-Hqn8H
https://www.youtube.com/playlist?list=PL0AQIMR-tpon97YXc8NepNnjoyoU1p7wT
https://www.youtube.com/playlist?list=PL0AQIMR-tpokPgGZ5Pa6c2C-7AIdSr8SN
https://www.youtube.com/playlist?list=PL0AQIMR-tpokLM4QIySmMeBSLO7fYeFyd
https://www.youtube.com/playlist?list=PL0AQIMR-tpolFb1c8IIwe749DYjt-aqQe
https://www.youtube.com/playlist?list=PL0AQIMR-tpolgy6cT-g6KfTvUpff-4bd7
https://www.youtube.com/playlist?list=PL0AQIMR-tpokhK9760lbeMYthNe7Sb-zD
https://www.youtube.com/playlist?list=PL0AQIMR-tpomx7dJiZtvnKYo9C1g4Vfzz
https://www.youtube.com/playlist?list=PL0AQIMR-tpokiqATQ76EG3DMbJD6BuaXa
https://www.youtube.com/playlist?list=PL0AQIMR-tpokK9vGSqLX4Hj6PsBCIyaBw
https://www.youtube.com/playlist?list=PL0AQIMR-tponqGjPp2tIPwjEodK8Q8lWf

The playlist containing every episodes (the two latest episodes are not yet tied to seasons so not having them in a "Season-playlist" is not a bug) : 
https://www.youtube.com/playlist?list=PL0AQIMR-tpolVRCh8SEK6V5Xi4mRJdFTL

**Comment by omarroth** [comment]
Should be fixed with a19cdb5e7251cb5b51d08e0c844119d8267440b3.

**Comment by TheFrenchGhosty** [comment]
It looks fixed on the search page but they are still not displayed on the playlists list page : https://invidio.us/channel/UCiH828EtgQjTyNIMH6YiOSw/playlists

Oh and also playlists pictures are now broken 
![playlists](https://user-images.githubusercontent.com/47571719/63204497-b6b5da80-c087-11e9-8f20-20b661be751f.png)

**Comment by TheFrenchGhosty** [comment]
https://github.com/omarroth/invidious/commit/2b94975345a3bdd085a99081de521d1c5d3ada48 fixed the problem.


The issue is now fixed.
