### ISSUE TITLE
RSS descriptions don't allow line break 

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#819]
https://github.com/lwindolf/liferea/issues/754

According to @lwindolf "the feed specifies text using ```<p style="white-space: pre">``` which means the feed explicitly specifies non-line breaking".

The problem is that as shown in the issue posted on Liferea's page, is that it makes  softwares that follow exactly the feed rules display a long line that isn't really user friendly.

**Comment by anoymouserver** [comment]
Does `white-space: pre-wrap` solve the problem?
It also preserves the newlines, but breaks the text if the available space isn't enough.

**Comment by omarroth** [comment]
Yep, should be fixed with 1e34a61911bf786497793b6fe3f309a411a32aae.

**Comment by TheFrenchGhosty** [comment]
Fixed.

**Comment by TheFrenchGhosty** [comment]
I noticed that it seems that the problem is still here for long links:

![invidious](https://user-images.githubusercontent.com/47571719/68081140-ff686e80-fe00-11e9-98b8-9ea4304a658d.gif)

As you can see in the gif, the only way for it not to happens is to adjust the size of the internal browser of Liferea.

**Comment by omarroth** [comment]
Should be fixed with f6ef0b684a05bc7f0260872268df484a77e78e7f.

**Comment by TheFrenchGhosty** [comment]
Fixed.
