### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by BurnyBoi** [omarroth/invidious#934]
Ever since going to the hotfix recently, watch pages are now loading again, but the error: "The media could not be loaded, either because the server or network failed or because the format is not supported." shows up on the video, and it doesn't play. Seems like once this happens, I have to wait a while before it stops doing it. Could this be another instance of Google trying to block Invidious from working?

**Comment by haizrul** [comment]
This problem only happen on certain videos. Most of the time on music videos (VEVO channels). E.g : https://invidio.us/watch?v=qCTMq7xvdXU

**Comment by omarroth** [comment]
Do you see any errors being logged in devtools?

**Comment by TheFoxStudio** [comment]
I can verify that this mostly happens to music videos. 
All my subscriptions around music are getting that error with no exception... trapcity, selected, NCS etc.
Came here in hope to find a solution for this as well.

**Comment by haizrul** [comment]
Should be working fine if admin use `local=true` in config.yml file, but this will increase the use of server bandwidth a lot.

**Comment by TheFoxStudio** [comment]
I read about the local=true statement in older issue posts about this problem. 
But there it was suggested to add it directly to the link as a value. That did not fix it for any of my videos.
Where exactly can I find the config.yml file to change it?

**Comment by TheFoxStudio** [comment]
The local=true does not fix the issue whatsoever.
"local=true" complete breaks the instance.
"local:true" doesn't work either. If there really is a reliable and reproducable fix for this media error problem it would be great if there would be some detailed infos or it would be added in official instructions / FAQ kinda stuff.

I really like invidious but it's kinda pointless if I can't run it to have some music on.

**Comment by thrdroom** [comment]
> it would be great if there would be some detailed infos or it would be added in official instructions / FAQ kinda stuff.
Im just guessing here, but i think there is no reliable fix atm, cause i have the same problem in the main instance at [https://invidio.us/](https://invidio.us)

> I really like invidious but it's kinda pointless if I can't run it to have some music on.
Same goes for me, in this state invidious is too much of a compromise for the needs of my friends which i want to host invidious for. I wish i could help to fix this problem.

**Comment by TheFoxStudio** [comment]
Completeley agree. I see this "add local=true" comment every time someone posts this issue so I assumed there is a fix and I do not see any comment on it by the dev so I felt like I am just to stupid to fix it.
I would love to help as well but honestly don't know where even to start.
This is a great product and I love that it helps me getting away from google but as you said, it's hard to use let alone get others to use if it lags this fundamental function.

I would really like to see any sort of comment by the dev to know if he is even aware/ working on this or if I can just purge this VM and use the space/power for other projects

**Comment by omarroth** [comment]
> "local=true" complete breaks the instance.

See #1046. This should be fixed with a117d87f331607864452b85c6066d972ce2cb568.

> Im just guessing here, but i think there is no reliable fix atm, cause i have the same problem in the main instance at https://invidio.us/

Do you encounter the same issue with `local=true`?

**Comment by TheFoxStudio** [comment]
Thank your for the feedback! 
I will check if this solves the problem. As I will upgrade my server anyway I guess its time for a fresh install that hopefully makes me completely independed.

**Comment by immanuelfodor** [comment]
Fresh build of master @ 6ff2229 and the video play only works if locale=true is removed, strange.

**Comment by immanuelfodor** [comment]
Console error:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
video.min.js:12:695
HTTP load failed with status 500. Load of media resource https://lan.local/latest_version?id=wqQYb2htN4U&itag=22&local=true failed.
```

**Comment by omarroth** [comment]
Closing in favor of #1046.
